#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# @Time    : 2019-07-09 19:50
# @Author  : Alex   alexzyq@outlook.com
# @FileName: excel_readAndWrite.py
# @Software: PyCharm

import openpyxl
from openpyxl import Workbook

# wb = Workbook()
# ws = wb.active
# ws['A1'] = 'hello'
# ws.append(['world','Life','is','beautifll'])
# wb.save('sample.xlsx')

# lwb = openpyxl.load_workbook('sample.xlsx')
# #
# ws = lwb['s1']
# ws['A2']='python'
# 
# lwb.save('sample.xlsx')
