#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# @Time    : 2019-07-11 19:46
# @Author  : Alex   alexzyq@outlook.com
# @FileName: create_calculator.py
# @Software: PyCharm


class Calculator():

    def __init__(self,a,b):
        self.a = a
        self.b = b

    def add(self):
        return self.a + self.b

    def sub(self):
        return self.a - self.b

    def mul(self):
        return self.a * self.b

    def div(self):
        return self.a / self.b
