#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# @Time    : 2019-07-11 19:51
# @Author  : Alex   alexzyq@outlook.com
# @FileName: test_calculator.py
# @Software: PyCharm

import unittest
from create_calculator import Calculator


class ModuleTest(unittest.TestCase):

    def setUp(self):
        self.cal = Calculator(8, 4)

    def tearDown(self):
        pass

    def test_add(self):
        result = self.cal.add()
        self.assertEqual(result, 12)

    def test_sub(self):
        result = self.cal.sub()
        self.assertEqual(result, 45)

    def test_mul(self):
        result = self.cal.mul()
        self.assertEqual(result, 323)

    def test_div(self):
        result = self.cal.div()
        self.assertEqual(result, 2)


if __name__ == '__main__':
    # unittest.main()
    suite = unittest.TestSuite()
    suite.addTest(ModuleTest('test_add'))
    suite.addTest(ModuleTest('test_sub'))
    suite.addTest(ModuleTest('test_mul'))
    suite.addTest(ModuleTest('test_div'))

    runner = unittest.TextTestRunner()
    runner.run(suite)

